theme: jekyll-theme-architect
title: Pocket Sampler
description: Projekt zaliczeniowy z przedmiotu Bogate Aplikacje Internetowe. Aplikacja dzięki której możemy zagrać tzw. live act z wcześniej już wgranych i przypisanych do danego guzika sampli muzycznych.